plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 130

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 35

Metrics/ParameterLists:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 30

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Enabled: false
